media:
  input: src/assets
  output: ../../assets
  categories: [image]
  rename: safe

content:
  - name: blog
    label: Blog
    type: collection
    path: src/content/blog
    format: yaml-frontmatter
    filename:
      template: '{primary}.md'
      field: create
    view:
      fields: [title, pubDate, published]
      primary: title
      sort: [pubDate, title]
      default:
        sort: pubDate
        order: desc
    fields:
      - name: title
        type: string
        required: true
      - name: subtitle
        type: string
      - name: description
        type: text
        required: true
      - name: pubDate
        type: date
        required: true
      - name: updatedDate
        type: date
      - name: tags
        type: string
        list: true
      - name: heroImage
        type: image
      - name: heroImageAlt
        type: string
      - name: published
        type: boolean
      - name: body
        type: rich-text

  - name: now
    label: Now
    type: collection
    path: src/content/now
    format: yaml-frontmatter
    filename:
      template: '{year}-{month}-{day}-{hour}-{minute}.md'
      field: create
    view:
      fields: [title, pubDate, published]
      primary: title
      sort: [pubDate]
      default:
        sort: pubDate
        order: desc
    fields:
      - name: title
        type: string
      - name: pubDate
        type: date
        required: true
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm
      - name: published
        type: boolean
      - name: body
        type: rich-text
        options:
          rename: true
          path: src/assets/now
          media: ../../assets/now
